apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bakingweb
  name: baking-web
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: baking-web
        image: 396304922437.dkr.ecr.us-east-1.amazonaws.com/baking_web_frontend:ede11478
        ports:
          - containerPort: 3000

