apiVersion: v1
kind: Service
metadata:
  name: baking-web-service
  namespace: bakingweb
spec:
  selector:
    app: my-app  # Match this with your Deployment's labels
  ports:
    - protocol: TCP
      port: 3000        # Service listens on 3000
      targetPort: 3000  # Container listens on 3000
      nodePort: 30080   # Node (EC2) exposes on 30080
  type: NodePort

