apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: backendweb
  labels: 
    app: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backndweb
          image: 396304922437.dkr.ecr.us-east-1.amazonaws.com/baking_web:c558e3ba
          ports:
            - containerPort: 8080
