apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: backendweb
  labels: 
    app: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backndweb
          image: dakshbhavsar/backend:v1
          ports:
            - containerPort: 8080
